import Head from 'next/head'
import Header from './components/home-page/header'
import MainContent from './components/home-page/main'
import Footer from './components/home-page/footer'


export default function Home() {
    return (
        <>
            <Head>
                <title>My Portfolio</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/"/>
            </Head>
            {/*<div className={'test'}>*/}
                <div className='content-wrapper'>
                    <div className='content-bg'>
                        <Header/>
                        <MainContent/>
                    </div>
                </div>
                <Footer/>
            {/*</div>*/}
        </>
    )
}
